### ISSUE TITLE
RuntimeError: Python version >= 3.6 required.

### ISSUE THREAD

**Issue by metegenez** [mc2-project/secure-xgboost#110]
Hi,

I am following the instructions for a demo. 

`sudo python3 setup.py install
`
is not working for me. For a reason that I couldnt figure out, it gives an error when I call it.

> Running scipy-1.5.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-1aT6QP/scipy-1.5.2/egg-dist-tmp-13I6Rd
> Traceback (most recent call last):
>   File "setup.py", line 59, in <module>
>     url='https://github.com/dmlc/xgboost')
>   File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 129, in setup
>     return distutils.core.setup(**attrs)
>   File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
>     dist.run_commands()
>   File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
>     self.run_command(cmd)
>   File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
>     cmd_obj.run()
>   File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 67, in run
>     self.do_egg_install()
>   File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
>     cmd.run()
>   File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 437, in run
>     self.easy_install(spec, not self.no_deps)
>   File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 679, in easy_install
>     return self.install_item(None, spec, tmpdir, deps, True)
>   File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 726, in install_item
>     self.process_distribution(spec, dist, deps)
>   File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 771, in process_distribution
>     [requirement], self.local_index, self.easy_install
>   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 774, in resolve
>     replace_conflicting=replace_conflicting
>   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1057, in best_match
>     return self.obtain(req, installer)
>   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1069, in obtain
>     return installer(requirement)
>   File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 698, in easy_install
>     return self.install_item(spec, dist.location, tmpdir, deps)
>   File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 724, in install_item
>     dists = self.install_eggs(spec, download, tmpdir)
>   File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 909, in install_eggs
>     return self.build_and_install(setup_script, setup_base)
>   File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1177, in build_and_install
>     self.run_setup(setup_script, setup_base, args)
>   File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1163, in run_setup
>     run_setup(setup_script, args)
>   File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 253, in run_setup
>     raise
>   File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
>     self.gen.throw(type, value, traceback)
>   File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
>     yield
>   File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
>     self.gen.throw(type, value, traceback)
>   File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 166, in save_modules
>     saved_exc.resume()
>   File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 141, in resume
>     six.reraise(type, exc, self._tb)
>   File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 154, in save_modules
>     yield saved
>   File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
>     yield
>   File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 250, in run_setup
>     _execfile(setup_script, ns)
>   File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 45, in _execfile
>     exec(code, globals, locals)
>   File "/tmp/easy_install-1aT6QP/scipy-1.5.2/setup.py", line 31, in <module>
>     # Please use setup_pip.py for generating and deploying pip installation
> RuntimeError: Python version >= 3.6 required.

I have python with version `Python 3.7.3`. What are the usual suspects for this error? Thank you for your effort. Also, no error on
`pip3 install numpy pandas sklearn numproto grpcio grpcio-tools   
`

**Comment by chester-leung** [comment]
Hi @metegenez,

Can you please paste the output of `which python3` and `which python`? I suspect that somehow `python3` is symlinked or aliased to your `python2.7`.

**Comment by metegenez** [comment]
`python3 --version` and `python --version` gives the same output. I eliminated that possibility.

**Comment by chester-leung** [comment]
Can you please outline the exact steps you ran before running `sudo python3 setup.py install`? Secure XGBoost has a Python requirement of `>= 3.4`, not 3.6, so I wonder if you may be accidentally installing something else.

This is the first few lines of the output during a successful installation of the Python package.
```
Install libxgboost from: ['../build/libxgboost.so']
running install
running bdist_egg
running egg_info
creating securexgboost.egg-info
writing securexgboost.egg-info/PKG-INFO
writing dependency_links to securexgboost.egg-info/dependency_links.txt
writing requirements to securexgboost.egg-info/requires.txt
writing top-level names to securexgboost.egg-info/top_level.txt
writing manifest file 'securexgboost.egg-info/SOURCES.txt'
reading manifest file 'securexgboost.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
```
